### ISSUE TITLE
/usr/bin/bash: line 203: kill: (1595723) - No such process

### ISSUE THREAD

**Issue by austintdaigle** [DrosophilaGenomeEvolution/TrEMOLO#13]
Hello,
I've been testing out tremolo (Insider+outsider, 32 cores) on a Drosophila genome assembly + nanopore reads, and am running into an issue at the very end of the pipeline. My installation and test run were successful as far as I can tell (no errors), and the pipeline ran for 15-18 hours, completing most tasks. My problem is that the output file POSITION_TE_OUTSIDER_ON_REF.bed has not been generated, which is the one I want most. There is an error called near the end of the output, which I have attached: 
<img width="604" alt="image" src="https://github.com/DrosophilaGenomeEvolution/TrEMOLO/assets/86490455/4e7ac18b-5df0-48ca-9eab-089400858981">

Also here is a screenshot of the outputs I do have: 
<img width="435" alt="image" src="https://github.com/DrosophilaGenomeEvolution/TrEMOLO/assets/86490455/06c68eb3-16d2-4f4a-af80-6fe6010f8650">

Happy to provide more details to figure this out. I've run this twice and got the same result.

**Comment by M-D75** [comment]
Hello,

The error `/usr/bin/bash: line 203: kill: (1595723) - No such process` is not a major issue; it occurs when the pipeline fails to stop the loading animation process of the tool. 

However, the missing `POSITION_TE_OUTSIDER_ON_REF.bed` file may be due to the following reasons:

- The integration step of OUTSIDER (`TE_TOWARD_GENOME`) into the assembly has failed.
- The OUTSIDERs were successfully integrated, but the annotation on the reference failed.

To determine where the problem lies i need to know whether the `INSIDER/TE_INSIDER_VR/TE_FOUND.csv` file is empty ?

if it is empty, check the `log/Snakefile_outsider.log` file, you should find information that looks like this :

```
CHECKING TE INTEGRATED...
TOTAL TE: 4; TE INTEGRATED ON GENOME TE_DB_ID: 4;
TOTAL TE: 4; TE INTEGRATED ON NEO GENOME: 4;
```

If all went well during the integration of OUTSIDER, you should see identical values for `TOTAL TE` and `TE INTEGRATE ON GENOME TE_DB_ID`. Please verify this information and keep me updated.

Best regards

**Comment by austintdaigle** [comment]
Thanks for the fast response! Looks like the integration step failed. In my INSIDER/TE_INSIDER_VR/ directory I don't even have a TE_FOUND.csv file

<img width="395" alt="image" src="https://github.com/DrosophilaGenomeEvolution/TrEMOLO/assets/86490455/9807718f-b176-4298-8456-64169f98bbb5">

In the log I see 0 integrations reported. 
<img width="457" alt="image" src="https://github.com/DrosophilaGenomeEvolution/TrEMOLO/assets/86490455/17f21efb-1c33-4675-ba8d-b6914bcb65c2">

Also here is a picture of my log file sizes, I noticed some that could be relevant are empty like FIND_TE_ON_REF.out
<img width="300" alt="image" src="https://github.com/DrosophilaGenomeEvolution/TrEMOLO/assets/86490455/f7ed79cd-9336-437b-b545-991698a8f7bf">

Couldn't find any obvious errors in the logs yet, looking forward to your response.

**Comment by M-D75** [comment]
Thank you.

Could you show me the contents of the `log/TE_TOWARD_GENOME.err` file?

**Comment by austintdaigle** [comment]
<img width="207" alt="image" src="https://github.com/DrosophilaGenomeEvolution/TrEMOLO/assets/86490455/2a07e9e8-928c-47cb-a038-8215062612d2">
I've attached a zip of all the log files in case that could be helpful. 
[log.zip](https://github.com/DrosophilaGenomeEvolution/TrEMOLO/files/13311797/log.zip)

**Comment by chao77777777** [comment]
Hellow，
I was able to use it normally last week. But then all of a sudden something went wrong, and I was confused.
When I use the test data，
CHECKING R PACKAGES...
MAKE REPORT
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
                                                                                                                       
BYE !
AN ERROR OCCURRED!
 
[SNK INFO] ERROR PIPELINE; snakefile used : work_test/SNAKE_USED/Snakefile_outsider.snk
    Check LOG   : work_test/log/Snakefile_outsider.log
    Check ERROR : work_test/log/Snakefile_outsider.err
/usr/bin/bash: line 197: kill: (136235) - No such process


When I use my own data，
Building DAG of jobs...
MissingInputException in line 137 of /storage2/TE_PE/TrEMOLO/Snakefile:
Missing input files for rule RENAME_PSEUDO_TE:
../YH_TIP/REPORT/report.html
LOADING DEACTIVATE
 
[SNK INFO] DRY RUN ERROR PIPELINE : please check your config file

 [SNK] DRY RUN DONE [ ✔ ] 

/usr/bin/bash: line 184: kill: (1873937) - No such process

Best wishes

**Comment by M-D75** [comment]
> <img alt="image" width="207" src="https://user-images.githubusercontent.com/86490455/281839019-2a07e9e8-928c-47cb-a038-8215062612d2.png"> I've attached a zip of all the log files in case that could be helpful. [log.zip](https://github.com/DrosophilaGenomeEvolution/TrEMOLO/files/13311797/log.zip)

Hello,

Thank you for providing the log files. I was able to identify the issue: in some cases, the TE integration script was not retrieving the chromosome from the genome correctly. 

The problem has been fixed, and an update is now available for download. The `TE_TOWARD_GENOME` step should proceed as expected, which I believe will solve the issue you encountered.

Please do not hesitate to let us know if everything goes well after the update, or if there are any other issues.

Thank you for reporting this.

**Comment by M-D75** [comment]
> Hellow， I was able to use it normally last week. But then all of a sudden something went wrong, and I was confused. When I use the test data， CHECKING R PACKAGES... MAKE REPORT Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
> 
> BYE ! AN ERROR OCCURRED!
> 
> [SNK INFO] ERROR PIPELINE; snakefile used : work_test/SNAKE_USED/Snakefile_outsider.snk Check LOG : work_test/log/Snakefile_outsider.log Check ERROR : work_test/log/Snakefile_outsider.err /usr/bin/bash: line 197: kill: (136235) - No such process
> 
> When I use my own data， Building DAG of jobs... MissingInputException in line 137 of /storage2/TE_PE/TrEMOLO/Snakefile: Missing input files for rule RENAME_PSEUDO_TE: ../YH_TIP/REPORT/report.html LOADING DEACTIVATE
> 
> [SNK INFO] DRY RUN ERROR PIPELINE : please check your config file
> 
> [SNK] DRY RUN DONE [ ✔ ]
> 
> /usr/bin/bash: line 184: kill: (1873937) - No such process
> 
> Best wishes


The issue you are experiencing when launching the tool on your own data stems from a recent update which, indeed, interferes with the proper execution of the **RENAME_PSEUDO_TE** step. An update has just been performed with the necessary corrections, sorry for that.

The problem you are facing with the test data may stem from the fact that during the penultimate update, the Singularity container was also modified, as the tool uses slightly different versions of R libraries to generate certain graphs in the report.html file. If you would like to avoid rebuilding the container, here is a link to a precompiled container: [TrEMOLO.simg](https://github.com/DrosophilaGenomeEvolution/TrEMOLO/releases/download/v2.4.0/TrEMOLO.simg)

Don't hesitate to report any other problems once you've downloaded the update.

Thank you for reporting this problem.

**Comment by M-D75** [comment]
> <img alt="image" width="207" src="https://user-images.githubusercontent.com/86490455/281839019-2a07e9e8-928c-47cb-a038-8215062612d2.png"> I've attached a zip of all the log files in case that could be helpful. [log.zip](https://github.com/DrosophilaGenomeEvolution/TrEMOLO/files/13311797/log.zip)

I am sorry once again, but I have identified another potential issue. If you have not performed an update before reading this message, then all is well. However, if you have already updated, please be aware that a new update is now available. I apologize for the inconvenience.

**Comment by chao77777777** [comment]
OK, 
Best wishes

**Comment by austintdaigle** [comment]
Awesome, thanks for working on this. Might take me a few days to rerun, but I'll report what happens here. Very excited to use this tool!

**Comment by austintdaigle** [comment]
Hello, just finished running this! Everything seems to be working well, I have all output files I was looking for and the TE integration seems to have been successful. 

TOTAL TE: 5530 ; TE INTEGRATE ON GENOME TE_DB_ID : 5529 ;
TOTAL TE: 5530 ; TE INTEGRATE ON NEO GENOME: 5529 ;

I am attaching the log files in case you wanted to look them over. Interestingly there seem to be a lot of errors in the TSD.err files, like "grep: /work/users/a/d/adaigle/tremolo_output3/OUTSIDER/TE_DETECTION/TSD/COUNT_READS.txt: No such file or directory". I don't know if this is a problem (I didn't include a FILE_SIZE_TE_TSD and some TSDs are being called), but mentioned it just in case. 
[log2.zip](https://github.com/DrosophilaGenomeEvolution/TrEMOLO/files/13383217/log2.zip)

Thanks again for your fast work on this. It has already been useful to my research!

**Comment by M-D75** [comment]
Hello,

I am delighted to know that your issue has been resolved. Thank you for your feedback, as well as for the log files provided; this is a great help in improving the tool.

Thank you,
M-D
