### ISSUE TITLE
/usr/bin/bash: line 196: kill: (1156106) - No such process

### ISSUE THREAD

**Issue by CrayonLinchan** [DrosophilaGenomeEvolution/TrEMOLO#15]
Hello,
**Firstly, I want to express my gratitude for providing such a remarkable tool!!!**
I have been experimenting with TrEMOLO (Insider) on two Arabidopsis thaliana genome assemblies and encountered an issue while identifying TSD. The installation was successful, as evidenced by a successful test run.
However, during the actual run, I encountered the following error:
`Building a new DB, current time: 12/11/2023 17:09:36
New DB name:   /test/TrEMOLO_OUTPUT/INPUT/PSEUDO_panEDTA.TElib.fasta
New DB title: /test/TrEMOLO_OUTPUT/INPUT/PSEUDO_panEDTA.TElib.fasta
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /test/TrEMOLO_OUTPUT/INPUT/PSEUDO_panEDTA.TElib.fasta
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 780 sequences in 0.0204461 seconds.
BYE !
AN ERROR OCCURRED!`
`[SNK INFO] ERROR PIPELINE; snakefile used : /test/TrEMOLO_OUTPUT/SNAKE_USED/Snakefile_insider.snk`
`snake log file : /test/TrEMOLO_OUTPUT/log/Snakefile_insider.log
 Error file : /test/TrEMOLO_OUTPUT/log/Snakefile_insider.err
/usr/bin/bash: line 196: kill: (1156106) - No such process`
Moreover, the detailed error information in Snakefile_insider.err is as follows:
`FASTA-Reader: Ignoring invalid residues at position(s): On line 11898: 38
/usr/bin/bash: line 191: count_task_running: unbound variable
[Mon Dec 11 10:48:37 2023]
Error in rule TSD_MULTI_THREADS:
    jobid: 2
    output: /test/TrEMOLO_OUTPUT/VALUES_TSD_INSIDER_GROUP.csv, /test/TrEMOLO_OUTPUT/tmp_TrEMOLO_output_rule/rule_tmp_TSD_MULTI_THREADS_TrEMOLO_OUTPUT
    log: /test/TrEMOLO_OUTPUT/log/TSD (check log file(s) for error message)`

I have been unable to identify the root cause of this problem. I would be happy to provide additional details to help resolve the issue.
Best regards

**Comment by CrayonLinchan** [comment]
Hello,

I wanted to express my sincere thanks for fixing this bug. With this updates, I reran the program successfully. I appreciate your quick and effective support. 
Looking forward to the upcoming update with the new TSD identification method. Thanks for the heads up!!

Best regards :)

**Comment by CrayonLinchan** [comment]
Hello again,
I encountered a new issue while running the Snakefile :( The specific error message in **Snakefile_insider.err** is as follows:
`rule REPORT:
    input: /test/TrEMOLO_OUTPUT/INPUT/tibet.fasta, /test/TrEMOLO_OUTPUT/tmp_TrEMOLO_output_rule/rule_tmp_TSD_MULTI_THREADS_TrEMOLO_OUTPUT
    output: /test/TrEMOLO_OUTPUT/REPORT/report.html
    log: /test/TrEMOLO_OUTPUT/log/REPORT
    jobid: 1

grep: /test/TrEMOLO_OUTPUT/INSIDER/FREQ_INSIDER/DEPTH_TE_INSIDER.csv: No such file or directory
`
In Snakefile_insider.log, the specific information is as follows:
`
[SNK]--[Thu 14 Dec 2023 01:09:17 PM CST] BUILD REPORT [^-^]
•••

[Thu 14 Dec 2023 01:09:17 PM CST] LOG TASK /test/TrEMOLO_OUTPUT/log/REPORT.out, /test/TrEMOLO_OUTPUT/log/REPORT.err
BUILD BED ALL INFOS...
CHECK INTERSECT TO DELETION INSIDER...
BUILD TE_INFO OUTSIDER...
BUILD FILE report.html...
  BUILD TSD CHART...
  BUILD chroms for scatter FREQUENCY js ...
  BUILD group for scatter FREQUENCY js ...
Warning: NO OUTSIDER IN REPORT
STRAND OUTSIDER
STRAND INSIDER
STRAND INOUTSIDER
ERROR: NO TE INSERTION FOUND
CHECKING R PACKAGES...
MAKE REPORT
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |.....                                                                 |   7%
   inline R code fragments


  |                                                                            
  |.........                                                             |  13%
label: init (with options) 
List of 1
 $ echo: logi FALSE


  |                                                                            
  |..............                                                        |  20%
  ordinary text without R code


  |                                                                            
  |...................                                                   |  27%
label: get_library (with options) 
List of 3
 $ eval   : logi TRUE
 $ include: logi TRUE
 $ results: logi FALSE


  |                                                                            
  |.......................                                               |  33%
  ordinary text without R code


  |                                                                            
  |............................                                          |  40%
label: PARAMETERS (with options) 
List of 3
 $ eval   : logi TRUE
 $ include: logi TRUE
 $ results: logi TRUE


  |                                                                            
  |.................................                                     |  47%
   inline R code fragments


  |                                                                            
  |.....................................                                 |  53%
label: COUNT_TE_INSIDER_INSERTION (with options) 
List of 4
 $ eval     : logi TRUE
 $ include  : logi TRUE
 $ results  : logi TRUE
 $ out.width: chr "90%"


AN ERROR OCCURRED!
 Error file : /test/TrEMOLO_OUTPUT/log/Snakefile_insider.err

`
Your help is greatly appreciated.
Best regards

**Comment by M-D75** [comment]
Hello,

I have received the email with a summary of the issue you identified. I hope you are no longer experiencing this problem, but I thank you for bringing it to our attention. The resolution of this issue will be carried out during the upcoming updates.

Thank you,
M-D
