### ISSUE TITLE
kill: (3066780) - No such process

### ISSUE THREAD

**Issue by chao77777777** [DrosophilaGenomeEvolution/TrEMOLO#16]
Hi，
![image](https://github.com/DrosophilaGenomeEvolution/TrEMOLO/assets/142374008/b31efd17-7c26-487a-be22-967b2c74c2c1)
It's strange that I still have this problem
Best regards,
Wang

**Comment by M-D75** [comment]
Hi,

There might be a problem with the new update, could you show me the `log/Snakefile_insider.err` file?

Thanks,
M-D

**Comment by chao77777777** [comment]
Hi，

[Snakefile_insider.err.txt](https://github.com/DrosophilaGenomeEvolution/TrEMOLO/files/13816214/Snakefile_insider.err.txt)

**Comment by M-D75** [comment]
Hi,

Thank you for reporting this issue, it actually concerns a permission matter: `/usr/bin/bash: line 205: /storage2/wangchao/TE_PEAR/TIP/TrEMOLO/lib/C++/bin/chain_to_id: Permission denied.` There's nothing too problematic to resolve, and we will perform an update later today with a fix for this issue. The pipeline will skip this step (which is not very important) if this problem occurs.

Thank you,
M-D

**Comment by M-D75** [comment]
Hi,

The update is now available, sorry for the wait.

Please do not hesitate to let us know if the problem persists or if you encounter any other issues.

sorry for the wait,
M-D

**Comment by chao77777777** [comment]
Hi，
Thank you for your timely repair. I will communicate with you in time if there is any problem.
Best regards,
Wang
