### ISSUE TITLE
LIFT_OFF Issue, no report

### ISSUE THREAD

**Issue by haoran-chn** [DrosophilaGenomeEvolution/TrEMOLO#19]
Hi,
Thank you for providing TrEMOLO!
I got an error when running test data via singularity.
Check the error message below:

> [SNK]--[Sun Apr 28 12:02:08 CEST 2024] LIFT_OFF 
•••

extracting features
@SQ     SN:Chr1 LN:30427671
@SQ     SN:Chr2 LN:19698289
@SQ     SN:Chr3 LN:23459830
@SQ     SN:Chr4 LN:18585056
@SQ     SN:Chr5 LN:26975502
@PG     ID:minimap2     PN:minimap2     VN:2.24-r1122   CL:minimap2 -d TrEMOLO_OUTPUT/INPUT/TAIR10.fa.mmi -a --end-bonus 5 --eqx -N 50 -p 0.5 -t 80 TrEMOLO_OUTPUT/INPUT/TAIR10.fa
aligning features
lifting features
AN ERROR OCCURRED!
 
[SNK INFO] ERROR PIPELINE; snakefile used : TrEMOLO_OUTPUT/SNAKE_USED/Snakefile_outsider.snk
    Check LOG   : TrEMOLO_OUTPUT/log/Snakefile_outsider.log
    Check ERROR : TrEMOLO_OUTPUT/log/Snakefile_outsider.err

Removing temporary output file TrEMOLO_OUTPUT/rep_tmp_snk.
[Sun Apr 28 12:03:04 2024]
Finished job 0.
1 of 1 steps (100%) done  

Complete log: snakemake/log/2024-04-28T114824.355614.snakemake.log
CHECKING OF DB TE....

I attached the err.log also, however I could not see any error in the LEFT_OFF.
Please let me if there is any solution and thanks in advance.
[LEFT_OFF.err.txt](https://github.com/DrosophilaGenomeEvolution/TrEMOLO/files/15141980/LEFT_OFF.err.txt)
[Snakefile_outsider.err.txt](https://github.com/DrosophilaGenomeEvolution/TrEMOLO/files/15141981/Snakefile_outsider.err.txt)

Haoran

**Comment by haoran-chn** [comment]
CalledProcessError in line 134 of /TrEMOLO/Snakefile:
Command 'set -euo pipefail;  kill -s 15 `ps -f | grep "TrEMOLO/lib/nodejs/load.js" 2>/dev/null | awk '$8=="node" {print $2}'` 2>/dev/null' returned non-zero exit status 2.
  File "/TrEMOLO/Snakefile", line 134, in __onerror

**Comment by haoran-chn** [comment]
/usr/bin/bash: line 68: DIFF_SIZE: unbound variable

**Comment by M-D75** [comment]
Hello,

Thank you for your interest in the pipeline.

Thank you for reporting the issue. I can already see where the error is; it should be simple to correct. An update will be made soon, and I will notify you once it has been completed.

Thank you again,
M-D

**Comment by M-D75** [comment]
Hi,
the update is available.
M-D

**Comment by haoran-chn** [comment]
Hi,

Thanks so much, I am going to test it. Which means I need to recompile it, right?

H.R

**Comment by M-D75** [comment]
Yeah, you just need to get the git update, either by performing a `git pull` in the **TrEMOLO** directory or by redoing a `git clone https://github.com/DrosophilaGenomeEvolution/TrEMOLO`. There is no need to rebuild the **Singularity** container.

I advise you to re-test the launch on the test dataset to ensure that no basic errors are present.

Best regards,
M-D
