### ISSUE TITLE
[SNK INFO] ERROR PIPELINE

### ISSUE THREAD

**Issue by UrsulaOggenfuss** [DrosophilaGenomeEvolution/TrEMOLO#9]
Hi, 
first thank you for creating and providing this important tool! 

I try to do the test run, but encounter several problems, and the error files are not helping me to really understand what went wrong (see attached file: [tremolo_output.txt](https://github.com/DrosophilaGenomeEvolution/TrEMOLO/files/11314949/tremolo_output.txt)). I had to install TrEMOLO via conda, as I don't have sudo rights on my universities cluster. Additionally, I installed all needed tools with conda, and R packes in R, and added `#include <stdio.h>` to TrEMOLO/lib/C++/chain_to_id.cpp.

My problem seems similar to #4 , yet I already encounter warnings earlier, and my log only contains the error files Snakefile_insider.err and Snakefile_outside.err, with the error 
```
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

I feel I'm missing something, and might have not installed a relevant tool, so I would really appreciate your input!
Thank you very much!
Ursula

**Comment by M-D75** [comment]
Hi,

Thank you for your feedback.

It seems that you have an old version of `coreutils`, the `tee` command does not find the `-p` option, which leads to an error:

```
tee: invalid option -- 'p'
Try 'tee --help' for more information.
```

TrEMOLO uses version `8.30`, you can try this command:

```
conda install -c "conda-forge/label/gcc7" coreutils=8.30
```

an update of the documentation will be done to add this information.

if you have singularity already installed on your cluster, I can provide you with a link to download an already built container, so you can run it without being `sudo`, this will hopefully make it easier for you to launch the tool.

Mourdas

**Comment by chaopear** [comment]
Hi，Thank you very much for providing this tool.
I'm having a similar problem, but since I built the environment myself, I'm not sure if there is a problem with my environment. Could you please send me the link to the built container, as I am not rooted.

**Comment by chaopear** [comment]
Hi，Thank you very much for providing this tool.
I'm having a similar problem, but since I built the environment myself, I'm not sure if there is a problem with my environment. Could you please send me the link to the built container, as I am not rooted.
Thanks !
wang

**Comment by chaopear** [comment]
Thank you very much!
Wang

**Comment by M-D75** [comment]
You're welcome, I hope this helps.

I advise you to use at least version `3.6.0+` of singularity if you have a version higher or equal to that one installed on your cluster

Mourdas

**Comment by chaopear** [comment]
Thanks for reminding, my version is 3.11.
Wang

**Comment by chaopear** [comment]
Thank you very much for providing the containers that have been built, it is indeed my own built environment that has the problem.
Wang

**Comment by UrsulaOggenfuss** [comment]
Thank you very much for the help! I ended up with a different tool for this specific (small part of a ) project, yet I will consider TrEMOLO for a future bigger project.
THank you very much for providing the tool and for the fast and helpful answer!

**Comment by M-D75** [comment]
Please, it's a pleasure to help you! I am delighted to hear that you have found a suitable solution for your current project. Thank you for your feedback.

Good luck with your projects !
